services:
  db:
    image: postgres
    expose: 
      - "5432"
    environment:
      - POSTGRES_PASSWORD=carlsarecool
      - POSTGRES_DB=carlsmart
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: on-failure

    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./pgdata:/var/lib/postgresql/data


  app:
    build: ./backend
    ports: 
      - "9000:5555"
