services:
  db:
    image: postgres
    expose: 
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=carlsarecool
      - POSTGRES_DB=carlmart
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: on-failure

    volumes:
      - ./pgdata:/var/lib/postgresql/data


  app:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - app